MultiChannelMedianFilterFloat5:
        ros__parameters:
                filter1:
                        name: median_test
                        type: MultiChannelMeanFilterFloat
                        params: {number_of_observations: 5} 
MultiChannelMedianFilterDouble5:
        ros__parameters:
                filter1:
                        name: median_test
                        type: MultiChannelMedianFilterDouble
                        params: {number_of_observations: 5} 
                        
        
