LowPass:
        ros__parameters:
                filter1:
                        name: transferfunction_test
                        type: MultiChannelTransferFunctionFilter
                        params: 
                              a: [1.0, -0.509525449494429]
                              b: [0.245237275252786, 0.245237275252786] 
LowPassSingle:
        ros__parameters:
                filter1:
                        name: transferfunction_test
                        type: SingleChannelTransferFunctionFilter<double>
                        params: 
                              a: [1.0, -0.509525449494429]
                              b: [0.245237275252786, 0.245237275252786]
LowPassNonUnity:
        ros__parameters:
                filter1:
                        name: transferfunction_test
                        type: MultiChannelTransferFunctionFilter<double>
                        params: 
                              a: [2.0, -0.509525449494429]
                              b: [0.245237275252786, 0.245237275252786]     
LowPassMulti:
        ros__parameters:
                filter1:
                        name: transferfunction_test
                        type: MultiChannelTransferFunctionFilter<double>
                        params: 
                              a: [1.0, -1.760041880343169, 1.182893262037831, -0.278059917634546]
                              b: [0.018098933007514, 0.245237275252786, 0.054296799022543, 0.018098933007514]    
LowPassIrrational:
        ros__parameters:
                filter1:
                        name: transferfunction_test
                        type: MultiChannelTransferFunctionFilter<double>
                        params: 
                              a: [1.0, -1.760041880343169, 1.182893262037831]
                              b: [0.018098933007514, 0.054296799022543, 0.054296799022543, 0.018098933007514]     

